### ISSUE TITLE
How to verify a password for a hashed passwords which were hashed with a secret

### ISSUE THREAD

**Issue by Kayxue** [felix-schindler/deno-argon2#5]
Just like the title, how to verify a password if hashed password hashed with a secret? I viewed the source codes and found out that it doesn't receive any secret to verify the password?

**Comment by felix-schindler** [comment]
Nice catch! This has been a bug for way too long.

I've just released [v2.0.0](https://github.com/felix-schindler/deno-argon2/releases/tag/v2.0.0). You can now verify a password hashed with a secret like this:

```ts
const encoder = new TextEncoder();
const secret = encoder.encode("this-is-geheim");
// Create password with given secret
const hashed = await hash(password, { secret });
// Verify password with given secret
const valid = await verify(hashed, password, secret);
```

If you notice anything else, please let me know :)
